services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    # volumes:
    #   - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables polling for file changes
    command: pnpm dev